global using DBFirstCRUDAPI.DBContext;
global using Microsoft.EntityFrameworkCore;
global using DBFirstCRUDAPI.Models;
global using System;
global using System.Collections.Generic;
global using Microsoft.EntityFrameworkCore.Metadata;
global using Microsoft.AspNetCore.Mvc;
global using DBFirstCRUDAPI.Services;
global using System.ComponentModel.DataAnnotations;